### PR TITLE
Added Framework::Matplotlib to setup.cfg

### PR DESCRIPTION
**Pull request by story645**
Was having trouble finding this package, couldn't remember the name. Figure this would have helped me and make it slightly more discoverable. Also, please consider adding this package to https://matplotlib.org/mpl-third-party/

### CODE REVIEW

**Comment by tomicapretto** [comment]
@story645 thanks for this PR! Flexitext is already in https://matplotlib.org/mpl-third-party/
image

maybe it should be in a different place?

**Comment by tomicapretto** [comment]
The failure is due to https://github.com/psf/black/issues/2964. Can you update `black` to 22.3.0 please?

**Comment by story645** [comment]
Sorry must have missed it by going too fast & I think the fix requires a reworking on that page. :/

**Comment by tomicapretto** [comment]
@story645 we can merge it now if you think it's ok! I'm not familiar with the Framework in setup.cfg but if you think it's fine, we can merge it

**Comment by story645** [comment]
I just followed the instructions on https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata but can move it to setup.py if you prefer

**Comment by tomicapretto** [comment]
It's fine! Thanks for the contribution!

And let me know if you have questions or suggestions about the library. I'm happy to help if possible :)

**Pull request merged**
